apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdfs-manager-role
rules:
  - apiGroups: ["storage.krea.to"]
    resources: ["volumes", "volumes/status", "engines", "engines/status", "replicas", "replicas/status", "snapshots", "snapshots/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "nodes", "persistentvolumes", "persistentvolumeclaims", "events", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "volumeattachments/status", "csinodes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
