name: CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - "build/**/Dockerfile"
      - "charts/**"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - "build/**/Dockerfile"
      - "charts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...

  build-images:
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/build-images.yml
    with:
      tag: dev
      push: true
