name: CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - "build/**/Dockerfile"
      - "charts/**"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - "build/**/Dockerfile"
      - "charts/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Install controller-gen
        run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
      - name: Generate deepcopy
        run: make generate
      - name: Build
        run: go build ./...
      - name: Test
        run: sudo -E go test ./...

  build-images:
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build-images.yml
    with:
      tag: dev
      push: true
